name: Create Firmware Release


on:

  workflow_dispatch:


  push:

    tags:

      - "v*"



jobs:


  release:


    runs-on: ubuntu-latest



    steps:


    - name: Checkout

      uses: actions/checkout@v4



    - name: Install Arduino CLI

      uses: arduino/setup-arduino-cli@v2



    - name: Install ESP32 Core

      run: |

        arduino-cli core update-index

        arduino-cli core install esp32:esp32



    - name: Build Firmware

      run: |

        arduino-cli compile \
        --fqbn esp32:esp32:esp32 \
        --output-dir firmware \
        examples/Basic



    - name: Prepare OTA Package

      run: |

        cp firmware/*.bin firmware/firmware.bin



        echo '{

        "name":"OpenIoT Device",

        "version":"${GITHUB_REF_NAME}",

        "firmware":"firmware.bin"

        }' > firmware/version.json



    - name: Create GitHub Release

      uses: softprops/action-gh-release@v2


      with:

        files: |

          firmware/firmware.bin

          firmware/version.json