name=OpenIoT
version=1.0.0
author=Md. Golam Mostofa
maintainer=Md. Golam Mostofa
sentence=Professional IoT Framework for ESP32 and ESP8266.
paragraph=OpenIoT Framework provides WiFi, Web Dashboard, GitHub OTA, JSON API, File System, Version Manager, Logging, and modular IoT services.
category=Communication
url=https://github.com/gmostofabd/OpenIoT-Framework
architectures=esp32,esp8266
includes=OpenIoT.h